### ISSUE TITLE
Customize livePlayer view

### ISSUE THREAD

**Issue by ArifJezir** [twilio/twilio-live-interactive-video#145]
**Question**
Is there any possibility to customize the Twilio Live player view?

**Additional context**
Our application to join above 30 members so we need to customize the live player view

Thanks.

**Comment by timmydoza** [comment]
Hi @ArifJezir - thanks for the question!

The view that is seen by the Twilio Live Player is powered by a [Media Extension](https://www.twilio.com/docs/live/media-extensions-overview), which is simply just a web application that connects to a Twilio Video Room and renders the participants. The audio and video from this web app is captured and broadcast to all of the Twilio Live Players.

This app uses a Media Extension hosted by Twilio called the [Video Composer](https://www.twilio.com/docs/live/video-composer). To customize the view seen by the Twilio Player, you can use your own web application as a Media Extension instead of Twilio's Video Composer. To use a custom Media Extension in this application, you'll just need to specify its URL in [this file here](https://github.com/twilio/twilio-live-interactive-video/blob/main/serverless/constants.js#L4). 

To make it easy to use a custom Media Extension, Twilio has an [open-source repository](https://github.com/twilio/twilio-media-extensions-quickstart) that you can clone and modify. This repository contains a copy of the source code that is used for the hosted `video-composer` that is already used by this app. This can make it easy to customize the appearance and behavior of the Video Composer. More information can be found in that repository, and in Twilio's [custom Media Extension documentation](https://www.twilio.com/docs/live/custom-composer).

I hope this gets you pointed in the right direction. Please let me know if you have any further questions!

**Comment by ArifJezir** [comment]
Okay Thanks for you replay.
