### ISSUE TITLE
"Swift" version

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-live-interactive-video#92]
Hi devs,
Is there a Swift&UIKit version of this project? Because SwiftUI supports minimum iOS 13, so most iOS developers don't know SwiftUI yet. Especially many projects also support lower versions of iOS 13, so we need "Swift" version of this project.

**Comment by timrozum** [comment]
Hi @HakanSAYAR, 

Thanks for the feedback. We don't have plans to implement this project in UIKit but there is a different project that could be useful.

https://github.com/twilio/twilio-video-app-ios is a video collaboration app that uses UIKit. It uses the video SDK for real-time video communication. But it has no streaming features that use Twilio Live or Sync. However the video collaboration UI is the most difficult UI work so hopefully this other repo is useful to pull from. The UI for stream viewers that uses Twilio Live is really simple to implement since it is just a single, composed video view. And so that should be pretty easy to convert.

Let me know if you have any more questions.
